<a href="https://colab.research.google.com/github/soadD/NBA-Web-Scapping-and-Data-Analysis/blob/main/Box_and_one_dinasty_DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Projeto com uma liga de Fantasy NBA : PARTE 2 - DA (Data Analysis)

Este projeto tem como fim tirar as principais análises dos times que foram aos playoffs (12) de uma liga de Fantasy Basketball formato dinastia. A partir deste serão coletadas métricas relevantes de como montar um time competitivo com chances de ganhar um título.

Dados:

Informações sobre times, colocações e rosters:

**MadHatter Fantasy Leagues**

 https://discord.gg/qXGxSbws

Estatísticas sobre jogadores, liga e tudo relacionado a basquete:

**nba_api**

https://github.com/swar/nba_api/tree/master?tab=readme-ov-file

**NBA Stats**

https://www.nba.com/stats

## Extração dos dados

### Importando times e seus jogadores que foram aos playoffs na liga Box-and-one Dinasty League

In [1]:
#Comando de abertura para google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Importação de bibliotecas
import pandas as pd

In [3]:
# Extração do csv da liga Box-and-one Dinasty
box = pd.read_csv('/content/drive/MyDrive/NBA/ETL/box_and_one_dinasty.csv')

### Importando tabela com todos os jogadores da NBA temporada 23-24

In [4]:
#Importando bibliotecas
import requests

In [5]:
#URL com estatísticas dos jogadores da NBA para a temporada regular de 23-24
url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2023-24&SeasonType=Regular%20Season&StatCategory=PTS'

In [6]:
#Importação dos arquivos dessa url para uma variável no ambiente virtual
r = requests.get(url=url).json()

In [7]:
#Como no JSON a descrição das estatísticas de cada jogador está armazenado em headers, vamos chamá-la como topo de tabela
table_headers = r['resultSet']['headers']

In [8]:
#Criação de dataframe com valores do json e nomeando as colunas com table_headers
players = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)

## Transformação

### Tipos de dados

In [9]:
# Verificação dos tipos de dados
box.dtypes

PLAYER_ID      int64
RANK           int64
PLAYER        object
TEAM_ID        int64
TEAM          object
GP             int64
MIN            int64
FGM            int64
FGA            int64
FG_PCT       float64
FG3M           int64
FG3A           int64
FG3_PCT      float64
FTM            int64
FTA            int64
FT_PCT       float64
OREB           int64
DREB           int64
REB            int64
AST            int64
STL            int64
BLK            int64
TOV            int64
PF             int64
PTS            int64
EFF            int64
AST_TOV      float64
STL_TOV      float64
team          object
dtype: object

In [10]:
# Transformar PLAYER_ID e TEAM_ID em object, renomear team para OWNER
# Convertendo o tipo de dados numéricos de float para int
box['PLAYER_ID'] = box['PLAYER_ID'].astype(str)
box['TEAM_ID'] = box['TEAM_ID'].astype(str)
box.rename(columns={'team': 'OWNER'}, inplace=True)

### Verificação de valores nulos

In [11]:
# Verificando valores nulos
box.isnull().sum()

PLAYER_ID    0
RANK         0
PLAYER       0
TEAM_ID      0
TEAM         0
GP           0
MIN          0
FGM          0
FGA          0
FG_PCT       0
FG3M         0
FG3A         0
FG3_PCT      0
FTM          0
FTA          0
FT_PCT       0
OREB         0
DREB         0
REB          0
AST          0
STL          0
BLK          0
TOV          0
PF           0
PTS          0
EFF          0
AST_TOV      0
STL_TOV      0
OWNER        0
dtype: int64

## Análise de Dados

Lembrete de gráficos importantes para análise de dados no Python:

Barras (horizontais quanto verticais - categoricas)
Setores (chamado gráfico de pizza/rosquinha - categoricas)
Linhas (series temporais)
Dispersão (numéricas)
Histograma (numéricas)
Boxplot (numéricas)
Adicionais

Mapas (se houver dados de cidades, estados, latitude, longitude)
Correlação (mapas de calor - heatmap)
Gráficos interativos (plotly)
Nuvem de palavras
Para os dashboards, recomenda-se:

Caixa de seleção
Cards
Grafico de Barras
Gráfico de Setores
Graficos de Linhas
Graficos de Mapas
Tabelas

### Descrição dos headers

Esta tabela está com os números Totais dos jogadores em toda a temporada de 23-24 da NBA. A descrição das siglas das colunas a seguir:


PLAYER_ID      ID do jogador

RANK           Classificação segundo a NBA

PLAYER         Nome do Jogador

TEAM_ID        ID do Time

TEAM           Time em que jogou na temporada

GP             Quantidade de jogos jogados na temporada

MIN            Quantidade total de minutos jogados

FGM            Arremessos convertidos

FGA            Arremessos tentados

FG_PCT         Relação entre arremessos convertidos e tentados

FG3M           Arremessos de 3 convertidos

FG3A           Arremessos de 3 tentados

FG3_PCT        Relação entre os arremessos de 3 convertidos e tentados

FTM            Lances livres convertidos

FTA            Lances livres tentados

FT_PCT         Relação entre os lances livres convertidos e tentados

OREB           Rebotes ofensivos pegos

DREB           Rebotes defensivos pegos

REB            Rebotes pegos

AST            Assistências

STL            Roubos de bola

BLK            Bloqueios

TOV            Perda de bola

PF             Faltas cometidas

PTS            Pontos

EFF            Eficiência (PTS + REB + AST + STL + BLK − Missed FG − Missed FT - TO) / GP

AST_TOV        Relação entre assistências/perdas de bola

STL_TOV        Relação entre roubos de bola/perdas de bola

OWNER          Time da liga de Fantasy que tem o jogador

A NBA não fornece as estatísticas de todos os jogadores por jogo pois alguns deles não jogam uma quantidade de minutos suficientes ou jogam muitos poucos jogos por temporada, tornando muito voláteis seus valores e dificultando estatísticas

### Manipulação básica dos dados

In [12]:
#Query simples
players[players['RANK'] == 202]

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
201,1630598,202,Aaron Wiggins,1610612760,OKC,78,1228,212,377,0.562,...,186,86,56,19,56,91,542,653,1.54,1.0

In [13]:
#Arranjo dos dados
box.sort_values(by='RANK', ascending=True)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV,OWNER
168,1629029,1,Luka Doncic,1610612742,DAL,70,2624,804,1652,0.487,...,686,99,38,282,149,2370,2580,2.43,0.35,duncandunker
41,203999,5,Nikola Jokic,1610612743,DEN,79,2737,822,1411,0.583,...,708,108,68,237,194,2085,3039,2.99,0.46,esri
110,1630162,6,Anthony Edwards,1610612750,MIN,79,2770,718,1558,0.461,...,405,101,42,241,141,2049,1863,1.68,0.42,ect
38,201142,7,Kevin Durant,1610612756,PHX,75,2791,751,1436,0.523,...,378,69,91,244,133,2032,2075,1.55,0.28,esri
22,1628369,8,Jayson Tatum,1610612738,BOS,74,2645,672,1426,0.471,...,364,75,43,188,145,1987,2045,1.94,0.40,luk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,203933,464,T.J. Warren,1610612750,MIN,11,125,18,41,0.439,...,9,4,1,4,11,41,49,2.25,1.00,esri
160,1641724,487,Jett Howard,1610612753,ORL,18,67,10,30,0.333,...,6,2,2,3,4,29,21,2.00,0.67,kyletime
16,1641735,498,Amari Bailey,1610612766,CHA,10,65,8,24,0.333,...,7,3,0,4,2,23,21,1.75,0.75,Buzz
15,1641816,507,Hunter Tyson,1610612743,DEN,18,48,8,20,0.400,...,2,1,0,2,10,20,18,1.00,0.50,Buzz
108,1641771,537,Jalen Slawson,1610612758,SAC,12,37,4,6,0.667,...,2,1,1,2,8,8,15,1.00,0.50,eraserlawnmower

### Transformação de Totais para por Jogo

In [14]:
# Novo dataset com valores per game (pg)
box_pg = box.copy()

In [15]:
# Colunas a ser transformadas
colunas_porjogo = [
    'MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA',
    'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

In [16]:
# Estrutura de repetição para fazer o calculo da média com base nos GP
for col in colunas_porjogo:
    box_pg[col] = (box_pg[col] / box_pg['GP']).round(1)

In [17]:
box_pg.dtypes

PLAYER_ID     object
RANK           int64
PLAYER        object
TEAM_ID       object
TEAM          object
GP             int64
MIN          float64
FGM          float64
FGA          float64
FG_PCT       float64
FG3M         float64
FG3A         float64
FG3_PCT      float64
FTM          float64
FTA          float64
FT_PCT       float64
OREB         float64
DREB         float64
REB          float64
AST          float64
STL          float64
BLK          float64
TOV          float64
PF           float64
PTS          float64
EFF            int64
AST_TOV      float64
STL_TOV      float64
OWNER         object
dtype: object

In [18]:
#Remover coluna eff
box_pg = box_pg.drop(columns=['EFF'])

In [19]:
#Conferindo conversão
box_pg.sort_values(by='RANK')

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,...,REB,AST,STL,BLK,TOV,PF,PTS,AST_TOV,STL_TOV,OWNER
168,1629029,1,Luka Doncic,1610612742,DAL,70,37.5,11.5,23.6,0.487,...,9.2,9.8,1.4,0.5,4.0,2.1,33.9,2.43,0.35,duncandunker
41,203999,5,Nikola Jokic,1610612743,DEN,79,34.6,10.4,17.9,0.583,...,12.4,9.0,1.4,0.9,3.0,2.5,26.4,2.99,0.46,esri
110,1630162,6,Anthony Edwards,1610612750,MIN,79,35.1,9.1,19.7,0.461,...,5.4,5.1,1.3,0.5,3.1,1.8,25.9,1.68,0.42,ect
38,201142,7,Kevin Durant,1610612756,PHX,75,37.2,10.0,19.1,0.523,...,6.6,5.0,0.9,1.2,3.3,1.8,27.1,1.55,0.28,esri
22,1628369,8,Jayson Tatum,1610612738,BOS,74,35.7,9.1,19.3,0.471,...,8.1,4.9,1.0,0.6,2.5,2.0,26.9,1.94,0.40,luk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,203933,464,T.J. Warren,1610612750,MIN,11,11.4,1.6,3.7,0.439,...,2.0,0.8,0.4,0.1,0.4,1.0,3.7,2.25,1.00,esri
160,1641724,487,Jett Howard,1610612753,ORL,18,3.7,0.6,1.7,0.333,...,0.4,0.3,0.1,0.1,0.2,0.2,1.6,2.00,0.67,kyletime
16,1641735,498,Amari Bailey,1610612766,CHA,10,6.5,0.8,2.4,0.333,...,0.9,0.7,0.3,0.0,0.4,0.2,2.3,1.75,0.75,Buzz
15,1641816,507,Hunter Tyson,1610612743,DEN,18,2.7,0.4,1.1,0.400,...,0.5,0.1,0.1,0.0,0.1,0.6,1.1,1.00,0.50,Buzz
108,1641771,537,Jalen Slawson,1610612758,SAC,12,3.1,0.3,0.5,0.667,...,0.6,0.2,0.1,0.1,0.2,0.7,0.7,1.00,0.50,eraserlawnmower

### Sleepers

Sleeper é um termo em ligas de fantasia para designar um jogador que tem potencial a qualquer momento a estourar na liga e aumentar bastante a sua margem de estatíscias. Este fenomeno ocorre por diversos motivos, como o jogador que compete a posição com ele foi trocado ou se lesionou, ele amadurece depois de alguns anos de adaptação na liga (terceiro ano de novatos, auge da carreira que geralmente é aos 27-29 anos).

Logo, procuraremos jogadores com maior diferença de rank entre o rank atual da nba e o seu Z score e a posição em que ele foi draftado e o OWNER que escolheu este jogador.

## Enriquecimento de Dataset

### Adicionando Z-Scores do Basketball Monster (BBM)

In [20]:
#Importação de Z-Scores
zscores = pd.read_csv('/content/drive/MyDrive/NBA/Zscores/zscores.csv')

In [21]:
#Transformar zscores em dataframe type
zscores = pd.DataFrame(zscores)

In [22]:
#Visualização do dataframe
zscores.head(1)

,Round,Rank,Value,Name,Team,Pos,Inj,g,m/g,p/g,...,2a/g,pV,3V,rV,aV,sV,bV,fg%V,ft%V,toV
0,1,1,"1,060554395",Joel Embiid,PHI,C,NaN,39,"33,57393162","34,69230769",...,"18,25641026","2,937799812","-0,3285533786","2,022542343","0,7595001018","0,5958714268","1,776745735","1,248958118","3,044786661","-2,512661268"

In [23]:
#Renomear "value" para "zscore"
zscores.rename(columns={'Value': 'Zscore'}, inplace=True)
zscores.rename(columns={'Rank': 'BBM_RANK'}, inplace=True)

In [24]:
# Selecionar apenas a coluna 'zscore' do dataframe zscores para dar merge com box_pg
zscores_subset = zscores[['Name', 'Zscore', 'BBM_RANK']]

In [25]:
#Verificando tipos em zscores_subset
zscores_subset.dtypes

Name        object
Zscore      object
BBM_RANK     int64
dtype: object

In [26]:
#Transformando Zscore para float convertendo virgulas para pontos
zscores_subset['Zscore'] = zscores_subset['Zscore'].str.replace(',', '.').astype(float)

<ipython-input-26-a73eebfdb44e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zscores_subset['Zscore'] = zscores_subset['Zscore'].str.replace(',', '.').astype(float)

In [27]:
#zscore com apenas 2 casas decimais
zscores_subset['Zscore'] = zscores_subset['Zscore'].round(2)

<ipython-input-27-68caaeee304e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zscores_subset['Zscore'] = zscores_subset['Zscore'].round(2)

In [28]:
#Assegurar que tanto zscores_subset quanto box_pg são DataFrames do pandas
zscores_subset = pd.DataFrame(zscores_subset)
box_pg = pd.DataFrame(box_pg)

In [29]:
#Deixando chave principal e chave estrangeira com mesmo nome
zscores_subset.rename(columns={'Name': 'PLAYER'}, inplace=True)

In [30]:
# Realizar o merge usando a coluna "PLAYER" como chave
box_df = pd.merge(box_pg, zscores_subset, on='PLAYER')

### Adicionando Matt Lawson Ranks para Box_df

In [32]:
#Importação de tabela
fbi = pd.read_csv('/content/drive/MyDrive/NBA/FBI Dinasty Rankings/FBI_dinasty_rankings.csv')

In [33]:
fbi = fbi.drop(col)

,Rank,Unnamed: 1,Player,Team,Unnamed: 4,Birthdate,Pos.,Age,Change,Projected Peak Stat Set,Stat Set Score
0,1,NaN,Victor Wembanyama,SAS,NaN,1/4/2004,C,20.5,0,FG% PTS 3PT REB AST STL BLK FT% TO,⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐⭐⭐⭐⭐⭐
1,2,NaN,Luka Dončić,DAL,NaN,2/28/1999,SF,25.4,0,FG% PTS 3PT REB AST STL BLK FT% TO,⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐
2,3,NaN,Shai Gilgeous-Alexander,OKC,NaN,7/12/1998,PG,26.0,0,FG% PTS 3PT REB AST STL BLK FT% TO,⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐
3,4,NaN,Nikola Jokić,DEN,NaN,2/19/1995,C,29.4,0,FG% PTS 3PT REB AST STL BLK FT% TO,⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐⭐⭐
4,5,NaN,Tyrese Haliburton,IND,NaN,2/29/2000,PG,24.4,0,FG% PTS 3PT REB AST STL BLK FT% TO,⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐
...,...,...,...,...,...,...,...,...,...,...,...
563,564,NaN,Malcolm Hill,NOR,NaN,10/26/1995,SF,28.7,-50,FG% PTS 3PT REB AST STL BLK FT% TO,NaN
564,565,NaN,James Johnson,IND,NaN,2/20/1987,PF,37.4,-32,Coming Soon,NaN
565,566,NaN,Pete Nance,CLE,NaN,2/19/2000,PF,24.4,-51,Coming Soon,NaN
566,567,NaN,Garrett Temple,TOR,NaN,5/8/1986,SF,38.2,-33,FG% PTS 3PT REB AST STL BLK FT% TO,❌❌❌❌❌❌❌❌❌❌
567,568,NaN,Taj Gibson,DET,NaN,6/24/1985,C,39.1,-33,FG% PTS 3PT REB AST STL BLK FT% TO,❌❌❌❌❌❌❌❌❌❌❌